# Generated by Django 2.2.2 on 2019-06-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("edc_data_manager", "0001_initial")]

    operations = [
        migrations.AlterModelManagers(name="crfqueryrule", managers=[]),
        migrations.AlterModelManagers(name="requisitionqueryrule", managers=[]),
    ]
