# Generated by Django 2.2 on 2019-06-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("edc_registration", "0017_auto_20190305_0123"),
        ("edc_data_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datamanagerquery", name="registered_subject"
        ),
        migrations.RemoveField(
            model_name="historicaldatamanagerquery", name="registered_subject"
        ),
        migrations.RemoveField(model_name="query", name="data_dictionary"),
        migrations.RemoveField(model_name="query", name="field_name"),
        migrations.RemoveField(model_name="query", name="visit_schedule"),
        migrations.AddField(
            model_name="query",
            name="data_dictionaries",
            field=models.ManyToManyField(
                blank=True,
                help_text="select all that apply",
                to="edc_data_manager.DataDictionary",
                verbose_name="Question(s)",
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="registered_subjects",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_registration.RegisteredSubject",
                verbose_name="Subject Identifier",
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="visit_schedules",
            field=models.ManyToManyField(
                blank=True,
                help_text="select all that apply",
                to="edc_data_manager.VisitSchedule",
                verbose_name="Visit(s)",
            ),
        ),
    ]
