# Generated by Django 2.2 on 2019-06-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0003_auto_20190606_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamanagerquery',
            name='title',
            field=models.CharField(blank=True, help_text='A short title describing this query', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldatamanagerquery',
            name='title',
            field=models.CharField(blank=True, help_text='A short title describing this query', max_length=35, null=True),
        ),
    ]
