# Generated by Django 2.2 on 2019-06-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0004_auto_20190606_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamanagerquery',
            name='response_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='historicaldatamanagerquery',
            name='response_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
