# Generated by Django 2.2 on 2019-06-06 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0005_auto_20190606_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamanagerquery',
            name='title',
        ),
        migrations.RemoveField(
            model_name='historicaldatamanagerquery',
            name='title',
        ),
        migrations.AlterField(
            model_name='datamanagerquery',
            name='recipient',
            field=models.ForeignKey(help_text='select a name from the list', on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Sent to'),
        ),
        migrations.AlterField(
            model_name='datamanagerquery',
            name='registered_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_registration.RegisteredSubject', verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='datamanagerquery',
            name='resolved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Has the query been satisfactorily resolved'),
        ),
        migrations.AlterField(
            model_name='historicaldatamanagerquery',
            name='resolved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Has the query been satisfactorily resolved'),
        ),
    ]
