# Generated by Django 2.2 on 2019-06-06 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edc_data_manager', '0006_auto_20190606_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamanagerquery',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='select a name from the list', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldatamanagerquery',
            name='resolved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='select a name from the list', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
