# Generated by Django 2.2.2 on 2019-06-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("edc_data_manager", "0006_auto_20190627_2303")]

    operations = [
        migrations.AlterField(
            model_name="crfqueryrule",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select any additional recipients. Users in the `Site Data Manager` group are automatically included.",
                related_name="_crfqueryrule_recipients_+",
                to="edc_data_manager.QueryUser",
                verbose_name="Send to",
            ),
        ),
        migrations.AlterField(
            model_name="dataquery",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select any additional recipients. Users in the `Site Data Manager` group are automatically included.",
                related_name="_dataquery_recipients_+",
                to="edc_data_manager.QueryUser",
                verbose_name="Sent to",
            ),
        ),
        migrations.AlterField(
            model_name="dataquery",
            name="sender",
            field=models.ForeignKey(
                help_text="Select a name from the list",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="edc_data_manager.DataManagerUser",
                verbose_name="Query raised by",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldataquery",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Select a name from the list",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_data_manager.DataManagerUser",
                verbose_name="Query raised by",
            ),
        ),
        migrations.AlterField(
            model_name="requisitionqueryrule",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select any additional recipients. Users in the `Site Data Manager` group are automatically included.",
                related_name="_requisitionqueryrule_recipients_+",
                to="edc_data_manager.QueryUser",
                verbose_name="Send to",
            ),
        ),
    ]
