# Generated by Django 2.2.2 on 2019-06-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("edc_data_manager", "0007_auto_20190628_2113")]

    operations = [
        migrations.RemoveIndex(
            model_name="dataquery", name="edc_data_ma_subject_0de66c_idx"
        ),
        migrations.AddIndex(
            model_name="dataquery",
            index=models.Index(
                fields=[
                    "subject_identifier",
                    "action_identifier",
                    "title",
                    "registered_subject",
                    "visit_schedule",
                ],
                name="edc_data_ma_subject_1343fe_idx",
            ),
        ),
    ]
