# Generated by Django 2.2.2 on 2019-07-06 05:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0008_auto_20190628_2247'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dataquery',
            name='edc_data_ma_subject_1343fe_idx',
        ),
        migrations.RenameField(
            model_name='dataquery',
            old_name='auto_generated',
            new_name='rule_generated',
        ),
        migrations.RenameField(
            model_name='historicaldataquery',
            old_name='auto_generated',
            new_name='rule_generated',
        ),
        migrations.RemoveField(
            model_name='historicaldataquery',
            name='auto_reference',
        ),
        migrations.AddField(
            model_name='crfqueryrule',
            name='reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
        migrations.AddField(
            model_name='crfqueryrule',
            name='rule_handler_name',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('lumbar_puncture_q13', 'Lumbar Puncture (Q13 ...)')], default='default', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dataquery',
            name='rule_reference',
            field=models.CharField(default=uuid.uuid4, max_length=150, null=True, verbose_name='Query rule reference'),
        ),
        migrations.AddField(
            model_name='historicalcrfqueryrule',
            name='reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
        migrations.AddField(
            model_name='historicalcrfqueryrule',
            name='rule_handler_name',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('lumbar_puncture_q13', 'Lumbar Puncture (Q13 ...)')], default='default', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicaldataquery',
            name='rule_reference',
            field=models.CharField(default=uuid.uuid4, max_length=150, null=True, verbose_name='Query rule reference'),
        ),
        migrations.AddField(
            model_name='historicalrequisitionqueryrule',
            name='reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
        migrations.AddField(
            model_name='historicalrequisitionqueryrule',
            name='rule_handler_name',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('lumbar_puncture_q13', 'Lumbar Puncture (Q13 ...)')], default='default', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='requisitionqueryrule',
            name='reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
        migrations.AddField(
            model_name='requisitionqueryrule',
            name='rule_handler_name',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('lumbar_puncture_q13', 'Lumbar Puncture (Q13 ...)')], default='default', max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dataquery',
            unique_together={('rule_reference', 'registered_subject', 'visit_schedule')},
        ),
        migrations.AddIndex(
            model_name='dataquery',
            index=models.Index(fields=['subject_identifier', 'action_identifier', 'title', 'rule_reference', 'registered_subject', 'visit_schedule'], name='edc_data_ma_subject_875fa1_idx'),
        ),
        migrations.RemoveField(
            model_name='dataquery',
            name='auto_reference',
        ),
    ]
