# Generated by Django 2.2 on 2019-06-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0008_auto_20190606_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamanagerquery',
            name='response_status',
            field=models.CharField(choices=[('New', 'New'), ('open', 'Open'), ('feedback', 'Feedback'), ('resolved', 'Resolved')], default='New', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicaldatamanagerquery',
            name='response_status',
            field=models.CharField(choices=[('New', 'New'), ('open', 'Open'), ('feedback', 'Feedback'), ('resolved', 'Resolved')], default='New', max_length=25),
        ),
    ]
