# Generated by Django 2.2.2 on 2019-07-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("edc_data_manager", "0009_auto_20190706_2156")]

    operations = [
        migrations.AddField(
            model_name="dataquery",
            name="locked",
            field=models.BooleanField(
                default=False, help_text="If locked, this query will NEVER be reopened."
            ),
        ),
        migrations.AddField(
            model_name="historicaldataquery",
            name="locked",
            field=models.BooleanField(
                default=False, help_text="If locked, this query will NEVER be reopened."
            ),
        ),
    ]
