# Generated by Django 2.2.2 on 2019-07-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0009_auto_20190713_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadictionary',
            name='model',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldatadictionary',
            name='model',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AddIndex(
            model_name='queryrule',
            index=models.Index(fields=['title', 'active'], name='edc_data_ma_title_c3118f_idx'),
        ),
    ]
