# Generated by Django 2.2 on 2019-06-06 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_data_manager', '0009_auto_20190606_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamanagerquery',
            name='visit_schedules',
        ),
        migrations.AddField(
            model_name='datamanagerquery',
            name='visit_schedule',
            field=models.ForeignKey(blank=True, help_text='select all that apply', null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_data_manager.VisitSchedule', verbose_name='Visit'),
        ),
        migrations.AddField(
            model_name='historicaldatamanagerquery',
            name='visit_schedule',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='select all that apply', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_data_manager.VisitSchedule', verbose_name='Visit'),
        ),
        migrations.AlterField(
            model_name='datamanagerquery',
            name='resolved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicaldatamanagerquery',
            name='resolved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25),
        ),
    ]
