# Generated by Django 4.2.5 on 2023-10-11 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edc_data_manager", "0030_alter_datadictionary_device_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataquery",
            name="visit_code_sequence",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(25),
                ],
                verbose_name="Visit code sequence",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldataquery",
            name="visit_code_sequence",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(25),
                ],
                verbose_name="Visit code sequence",
            ),
        ),
    ]
