# Generated by Django 4.2.7 on 2023-11-28 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("edc_data_manager", "0032_validationerrors_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ValidationErrors",
        ),
    ]
