# Generated by Django 4.2.7 on 2023-11-28 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("edc_form_runners", "0001_initial"),
        ("edc_data_manager", "0033_delete_validationerrors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[],
            options={
                "verbose_name": "Form validation issue",
                "verbose_name_plural": "Form validation issues",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("edc_form_runners.issue",),
        ),
    ]
