# Generated by Django 5.0 on 2024-01-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edc_data_manager", "0038_alter_historicalqueryrule_rule_handler_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalqueryrule",
            name="rule_handler_name",
            field=models.CharField(
                choices="(('do_nothing', 'Do Nothing'), ('default', 'Default'))",
                default="default",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="queryrule",
            name="rule_handler_name",
            field=models.CharField(
                choices="(('do_nothing', 'Do Nothing'), ('default', 'Default'))",
                default="default",
                max_length=150,
            ),
        ),
    ]
